class Category_1410 {
class RH_hk416 { type = "trade_weapons"; buy[] ={6000,"Coins"}; sell[] ={3000,"Coins"}; };
class RH_hk416s { type = "trade_weapons"; buy[] ={6000,"Coins"}; sell[] ={3000,"Coins"}; };
class RH_hk416saim { type = "trade_weapons"; buy[] ={6500,"Coins"}; sell[] ={3250,"Coins"}; };
class RH_hk416seotech { type = "trade_weapons"; buy[] ={6500,"Coins"}; sell[] ={3250,"Coins"}; };
class RH_hk416sacog { type = "trade_weapons"; buy[] ={7000,"Coins"}; sell[] ={3500,"Coins"}; };
class RH_hk416sd { type = "trade_weapons"; buy[] ={8000,"Coins"}; sell[] ={4000,"Coins"}; };
class RH_hk416sdaim { type = "trade_weapons"; buy[] ={8500,"Coins"}; sell[] ={4250,"Coins"}; };
class RH_hk416sdeotech { type = "trade_weapons"; buy[] ={8500,"Coins"}; sell[] ={4250,"Coins"}; };
class RH_hk416aim { type = "trade_weapons"; buy[] ={6500,"Coins"}; sell[] ={3250,"Coins"}; };
class RH_hk416eotech { type = "trade_weapons"; buy[] ={6500,"Coins"}; sell[] ={3250,"Coins"}; };
class RH_hk416acog { type = "trade_weapons"; buy[] ={7000,"Coins"}; sell[] ={3500,"Coins"}; };
class RH_hk416gl { type = "trade_weapons"; buy[] ={6300,"Coins"}; sell[] ={3150,"Coins"}; };
class RH_hk416glaim { type = "trade_weapons"; buy[] ={6800,"Coins"}; sell[] ={3400,"Coins"}; };
class RH_hk416gleotech { type = "trade_weapons"; buy[] ={6800,"Coins"}; sell[] ={3400,"Coins"}; };
class RH_hk416glacog { type = "trade_weapons"; buy[] ={7300,"Coins"}; sell[] ={3650,"Coins"}; };
class RH_hk416sgl { type = "trade_weapons"; buy[] ={6300,"Coins"}; sell[] ={3150,"Coins"}; };
class RH_hk416sglaim { type = "trade_weapons"; buy[] ={6800,"Coins"}; sell[] ={3400,"Coins"}; };
class RH_hk416sgleotech { type = "trade_weapons"; buy[] ={7300,"Coins"}; sell[] ={3650,"Coins"}; };
class RH_hk416sglacog { type = "trade_weapons"; buy[] ={7300,"Coins"}; sell[] ={3650,"Coins"}; };
class RH_hk416sdgl { type = "trade_weapons"; buy[] ={8300,"Coins"}; sell[] ={4150,"Coins"}; };
 class vil_HK416_Aim {
            type = "trade_weapons";
            buy[] ={6300,"Coins"};
            sell[] ={3600,"Coins"};
        };
        class vil_HK416_IS {
            type = "trade_weapons";
            buy[] ={5400,"Coins"};
            sell[] ={3600,"Coins"};
        };
        class vil_HK416_EOT {
            type = "trade_weapons";
            buy[] ={7200,"Coins"};
            sell[] ={3600,"Coins"};
        };
        class vil_HK416_GL {
            type = "trade_weapons";
            buy[] ={7200,"Coins"};
            sell[] ={3600,"Coins"};
        };
        class VIL_HK416_EDR {
            type = "trade_weapons";
            buy[] ={9000,"Coins"};
            sell[] ={6300,"Coins"};
        };
class RH_hk416sdglaim { type = "trade_weapons"; buy[] ={8800,"Coins"}; sell[] ={4400,"Coins"}; };
class RH_hk416sdgleotech { type = "trade_weapons"; buy[] ={8800,"Coins"}; sell[] ={4400,"Coins"}; };
};
class Category_1420 {
class RH_hk417 { type = "trade_weapons"; buy[] ={15000,"Coins"}; sell[] ={7500,"Coins"}; };
class RH_hk417aim { type = "trade_weapons"; buy[] ={15500,"Coins"}; sell[] ={7750,"Coins"}; };
class RH_hk417eotech { type = "trade_weapons"; buy[] ={15500,"Coins"}; sell[] ={7750,"Coins"}; };
class RH_hk417acog { type = "trade_weapons"; buy[] ={16000,"Coins"}; sell[] ={8000,"Coins"}; };
class RH_hk417sp { type = "trade_weapons"; buy[] ={15200,"Coins"}; sell[] ={7600,"Coins"}; };
class RH_hk417s { type = "trade_weapons"; buy[] ={15000,"Coins"}; sell[] ={7500,"Coins"}; };
class RH_hk417saim { type = "trade_weapons"; buy[] ={15500,"Coins"}; sell[] ={7750,"Coins"}; };
class RH_hk417seotech { type = "trade_weapons"; buy[] ={15500,"Coins"}; sell[] ={7750,"Coins"}; };
class RH_hk417sacog { type = "trade_weapons"; buy[] ={16000,"Coins"}; sell[] ={8000,"Coins"}; };
class RH_hk417sd { type = "trade_weapons"; buy[] ={17000,"Coins"}; sell[] ={8500,"Coins"}; };
class RH_hk417sdaim { type = "trade_weapons"; buy[] ={17500,"Coins"}; sell[] ={8750,"Coins"}; };
class RH_hk417sdeotech { type = "trade_weapons"; buy[] ={17500,"Coins"}; sell[] ={8750,"Coins"}; };
class RH_hk417sdacog { type = "trade_weapons"; buy[] ={18000,"Coins"}; sell[] ={9000,"Coins"}; };
class RH_hk417sdsp { type = "trade_weapons"; buy[] ={19000,"Coins"}; sell[] ={9500,"Coins"}; };
class RH_hk417sgl { type = "trade_weapons"; buy[] ={15300,"Coins"}; sell[] ={7650,"Coins"}; };
class RH_hk417sglaim { type = "trade_weapons"; buy[] ={15800,"Coins"}; sell[] ={7900,"Coins"}; };
class RH_hk417sgleotech { type = "trade_weapons"; buy[] ={16300,"Coins"}; sell[] ={8150,"Coins"}; };
class RH_hk417sglacog { type = "trade_weapons"; buy[] ={16300,"Coins"}; sell[] ={8150,"Coins"}; };
};
class Category_1430 {
class RH_ctar21 { type = "trade_weapons"; buy[] ={6000,"Coins"}; sell[] ={3000,"Coins"}; };
class RH_ctar21glacog { type = "trade_weapons"; buy[] ={6800,"Coins"}; sell[] ={3400,"Coins"}; };
class RH_ctar21m { type = "trade_weapons"; buy[] ={6500,"Coins"}; sell[] ={3250,"Coins"}; };
class RH_ctar21mgl { type = "trade_weapons"; buy[] ={6800,"Coins"}; sell[] ={3400,"Coins"}; };
class RH_star21 { type = "trade_weapons"; buy[] ={7000,"Coins"}; sell[] ={3500,"Coins"}; };
};
class Category_1440 {
class RH_mas { type = "trade_weapons"; buy[] ={6000,"Coins"}; sell[] ={3000,"Coins"}; };
class RH_masaim { type = "trade_weapons"; buy[] ={6500,"Coins"}; sell[] ={3250,"Coins"}; };
class RH_maseotech { type = "trade_weapons"; buy[] ={6500,"Coins"}; sell[] ={3250,"Coins"}; };
class RH_masacog { type = "trade_weapons"; buy[] ={7000,"Coins"}; sell[] ={3500,"Coins"}; };
class RH_massd { type = "trade_weapons"; buy[] ={8000,"Coins"}; sell[] ={4000,"Coins"}; };
class RH_massdaim { type = "trade_weapons"; buy[] ={8500,"Coins"}; sell[] ={4250,"Coins"}; };
class RH_massdeotech { type = "trade_weapons"; buy[] ={8500,"Coins"}; sell[] ={4250,"Coins"}; };
class RH_massdacog { type = "trade_weapons"; buy[] ={9000,"Coins"}; sell[] ={4500,"Coins"}; };
class RH_masb { type = "trade_weapons"; buy[] ={6000,"Coins"}; sell[] ={3000,"Coins"}; };
class RH_masbaim { type = "trade_weapons"; buy[] ={6500,"Coins"}; sell[] ={3250,"Coins"}; };
class RH_masbeotech { type = "trade_weapons"; buy[] ={6500,"Coins"}; sell[] ={3250,"Coins"}; };
class RH_masbacog { type = "trade_weapons"; buy[] ={7000,"Coins"}; sell[] ={3500,"Coins"}; };
class RH_masbsd { type = "trade_weapons"; buy[] ={8000,"Coins"}; sell[] ={4000,"Coins"}; };
class RH_masbsdaim { type = "trade_weapons"; buy[] ={8500,"Coins"}; sell[] ={4250,"Coins"}; };
class RH_masbsdeotech { type = "trade_weapons"; buy[] ={8500,"Coins"}; sell[] ={4250,"Coins"}; };
class RH_masbsdacog { type = "trade_weapons"; buy[] ={9000,"Coins"}; sell[] ={4500,"Coins"}; };
};
class Category_1450 {
class RH_m14 { type = "trade_weapons"; buy[] ={18000,"Coins"}; sell[] ={9000,"Coins"}; };
class RH_m14acog { type = "trade_weapons"; buy[] ={18000,"Coins"}; sell[] ={9000,"Coins"}; };
class RH_m14aim { type = "trade_weapons"; buy[] ={18000,"Coins"}; sell[] ={9000,"Coins"}; };
class RH_m14eot { type = "trade_weapons"; buy[] ={18000,"Coins"}; sell[] ={9000,"Coins"}; };
class RH_m21 { type = "trade_weapons"; buy[] ={20000,"Coins"}; sell[] ={10000,"Coins"}; };
class RH_sc2 { type = "trade_weapons"; buy[] ={20000,"Coins"}; sell[] ={10000,"Coins"}; };
class RH_sc2acog { type = "trade_weapons"; buy[] ={20000,"Coins"}; sell[] ={10000,"Coins"}; };
class RH_sc2aim { type = "trade_weapons"; buy[] ={20000,"Coins"}; sell[] ={10000,"Coins"}; };
class RH_sc2eot { type = "trade_weapons"; buy[] ={20000,"Coins"}; sell[] ={10000,"Coins"}; };
class RH_sc2shd { type = "trade_weapons"; buy[] ={20000,"Coins"}; sell[] ={10000,"Coins"}; };
class RH_sc2sp { type = "trade_weapons"; buy[] ={20000,"Coins"}; sell[] ={10000,"Coins"}; };
class RH_m1s { type = "trade_weapons"; buy[] ={20000,"Coins"}; sell[] ={10000,"Coins"}; };
class RH_m1sacog { type = "trade_weapons"; buy[] ={20000,"Coins"}; sell[] ={10000,"Coins"}; };
class RH_m1saim { type = "trade_weapons"; buy[] ={20000,"Coins"}; sell[] ={10000,"Coins"}; };
class RH_m1seot { type = "trade_weapons"; buy[] ={20000,"Coins"}; sell[] ={10000,"Coins"}; };
class RH_m1sshd { type = "trade_weapons"; buy[] ={20000,"Coins"}; sell[] ={10000,"Coins"}; };
class RH_m1ssp { type = "trade_weapons"; buy[] ={20000,"Coins"}; sell[] ={10000,"Coins"}; };
class RH_m1st { type = "trade_weapons"; buy[] ={20000,"Coins"}; sell[] ={10000,"Coins"}; };
class RH_m1stacog { type = "trade_weapons"; buy[] ={20000,"Coins"}; sell[] ={10000,"Coins"}; };
class RH_m1staim { type = "trade_weapons"; buy[] ={20000,"Coins"}; sell[] ={10000,"Coins"}; };
class RH_m1steot { type = "trade_weapons"; buy[] ={20000,"Coins"}; sell[] ={10000,"Coins"}; };
class RH_m1stshd { type = "trade_weapons"; buy[] ={20000,"Coins"}; sell[] ={10000,"Coins"}; };
class RH_m1stsp { type = "trade_weapons"; buy[] ={20000,"Coins"}; sell[] ={10000,"Coins"}; };
class vil_SR25 { type = "trade_weapons"; buy[] ={20000,"Coins"}; sell[] ={10000,"Coins"}; };
class vil_M110 { type = "trade_weapons"; buy[] ={20000,"Coins"}; sell[] ={10000,"Coins"}; };
class vil_HK417s { type = "trade_weapons"; buy[] ={15000,"Coins"}; sell[] ={7500,"Coins"}; };
class vil_SR25SD { type = "trade_weapons"; buy[] ={20000,"Coins"}; sell[] ={10000,"Coins"}; };
class vil_M110sd { type = "trade_weapons"; buy[] ={20000,"Coins"}; sell[] ={10000,"Coins"}; };
class vil_M21G { type = "trade_weapons"; buy[] ={20000,"Coins"}; sell[] ={10000,"Coins"}; };
class vil_M14G { type = "trade_weapons"; buy[] ={18000,"Coins"}; sell[] ={9000,"Coins"}; };
};
class Category_1460 {
class SCAR_L_CQC { type = "trade_weapons"; buy[] ={8000,"Coins"}; sell[] ={4000,"Coins"}; };
class SCAR_L_CQC_Holo { type = "trade_weapons"; buy[] ={8500,"Coins"}; sell[] ={4250,"Coins"}; };
class SCAR_L_STD_Mk4CQT { type = "trade_weapons"; buy[] ={9000,"Coins"}; sell[] ={4500,"Coins"}; };
class SCAR_L_STD_EGLM_RCO { type = "trade_weapons"; buy[] ={8800,"Coins"}; sell[] ={4400,"Coins"}; };
class SCAR_L_CQC_EGLM_Holo { type = "trade_weapons"; buy[] ={9300,"Coins"}; sell[] ={4650,"Coins"}; };
class SCAR_L_STD_HOLO { type = "trade_weapons"; buy[] ={8500,"Coins"}; sell[] ={4250,"Coins"}; };
class SCAR_L_CQC_CCO_SD { type = "trade_weapons"; buy[] ={9500,"Coins"}; sell[] ={4750,"Coins"}; };
class SCAR_H_CQC_CCO { type = "trade_weapons"; buy[] ={15500,"Coins"}; sell[] ={7750,"Coins"}; };
class SCAR_H_CQC_CCO_SD { type = "trade_weapons"; buy[] ={17500,"Coins"}; sell[] ={8750,"Coins"}; };
class SCAR_H_STD_EGLM_Spect { type = "trade_weapons"; buy[] ={16000,"Coins"}; sell[] ={8000,"Coins"}; };
class SCAR_H_LNG_Sniper { type = "trade_weapons"; buy[] ={17000,"Coins"}; sell[] ={8500,"Coins"}; };
class SCAR_H_LNG_Sniper_SD { type = "trade_weapons"; buy[] ={19000,"Coins"}; sell[] ={9500,"Coins"}; };
};
class Category_1470 {
class vil_G3a3 { type = "trade_weapons"; buy[] ={15000,"Coins"}; sell[] ={5000,"Coins"}; };
class vil_G3a2 { type = "trade_weapons"; buy[] ={15000,"Coins"}; sell[] ={5000,"Coins"}; };
class vil_G3a4 { type = "trade_weapons"; buy[] ={15000,"Coins"}; sell[] ={5000,"Coins"}; };
class vil_G3a4b { type = "trade_weapons"; buy[] ={15000,"Coins"}; sell[] ={5000,"Coins"}; };
class vil_G3an { type = "trade_weapons"; buy[] ={15000,"Coins"}; sell[] ={5000,"Coins"}; };
class vil_G3anb { type = "trade_weapons"; buy[] ={15000,"Coins"}; sell[] ={5000,"Coins"}; };
class vil_G3ZF { type = "trade_weapons"; buy[] ={27000,"Coins"}; sell[] ={9000,"Coins"}; };
class vil_G3zfb { type = "trade_weapons"; buy[] ={27000,"Coins"}; sell[] ={9000,"Coins"}; };
class vil_G3SG1 { type = "trade_weapons"; buy[] ={27000,"Coins"}; sell[] ={9000,"Coins"}; };
class vil_G3sg1b { type = "trade_weapons"; buy[] ={27000,"Coins"}; sell[] ={9000,"Coins"}; };
class vil_G3TGS { type = "trade_weapons"; buy[] ={15000,"Coins"}; sell[] ={5000,"Coins"}; };
class vil_G3TGSb { type = "trade_weapons"; buy[] ={15000,"Coins"}; sell[] ={5000,"Coins"}; };
class vil_AG3 { type = "trade_weapons"; buy[] ={15000,"Coins"}; sell[] ={5000,"Coins"}; };
class vil_AG3EOT { type = "trade_weapons"; buy[] ={15000,"Coins"}; sell[] ={5000,"Coins"}; };
class SCAR_H_LNG_Sniper_SD { type = "trade_weapons"; buy[] ={19000,"Coins"}; sell[] ={9500,"Coins"}; };
};
class Category_1480 {
class FHQ_ACR_WDL_IRN { type = "trade_weapons"; buy[] ={8000,"Coins"}; sell[] ={4000,"Coins"}; };
class FHQ_ACR_WDL_IRN_F { type = "trade_weapons"; buy[] ={8000,"Coins"}; sell[] ={4000,"Coins"}; };
class FHQ_ACR_WDL_IRN_GL { type = "trade_weapons"; buy[] ={8300,"Coins"}; sell[] ={4150,"Coins"}; };
class FHQ_ACR_WDL_IRN_GL_F { type = "trade_weapons"; buy[] ={8300,"Coins"}; sell[] ={4150,"Coins"}; };
class FHQ_ACR_WDL_CCO { type = "trade_weapons"; buy[] ={8500,"Coins"}; sell[] ={4250,"Coins"}; };
class FHQ_ACR_WDL_CCO_F { type = "trade_weapons"; buy[] ={8500,"Coins"}; sell[] ={4250,"Coins"}; };
class FHQ_ACR_WDL_CCO_GL { type = "trade_weapons"; buy[] ={8800,"Coins"}; sell[] ={4400,"Coins"}; };
class FHQ_ACR_WDL_CCO_GL_F { type = "trade_weapons"; buy[] ={8800,"Coins"}; sell[] ={4400,"Coins"}; };
class FHQ_ACR_WDL_RCO { type = "trade_weapons"; buy[] ={9500,"Coins"}; sell[] ={4750,"Coins"}; };
class FHQ_ACR_WDL_RCO_F { type = "trade_weapons"; buy[] ={9500,"Coins"}; sell[] ={4750,"Coins"}; };
class FHQ_ACR_WDL_RCO_GL { type = "trade_weapons"; buy[] ={9800,"Coins"}; sell[] ={4900,"Coins"}; };
class FHQ_ACR_WDL_RCO_GL_F { type = "trade_weapons"; buy[] ={9800,"Coins"}; sell[] ={4900,"Coins"}; };
class FHQ_ACR_WDL_HWS { type = "trade_weapons"; buy[] ={8500,"Coins"}; sell[] ={4250,"Coins"}; };
class FHQ_ACR_WDL_HWS_F { type = "trade_weapons"; buy[] ={8500,"Coins"}; sell[] ={4250,"Coins"}; };
class FHQ_ACR_WDL_HWS_GL { type = "trade_weapons"; buy[] ={8800,"Coins"}; sell[] ={4400,"Coins"}; };
class FHQ_ACR_WDL_HWS_GL_F { type = "trade_weapons"; buy[] ={8800,"Coins"}; sell[] ={4400,"Coins"}; };
class FHQ_ACR_WDL_G33 { type = "trade_weapons"; buy[] ={9500,"Coins"}; sell[] ={4750,"Coins"}; };
class FHQ_ACR_WDL_G33_F { type = "trade_weapons"; buy[] ={9500,"Coins"}; sell[] ={4750,"Coins"}; };
class FHQ_ACR_WDL_G33_GL { type = "trade_weapons"; buy[] ={9800,"Coins"}; sell[] ={4900,"Coins"}; };
class FHQ_ACR_WDL_G33_GL_F { type = "trade_weapons"; buy[] ={9800,"Coins"}; sell[] ={4900,"Coins"}; };
class FHQ_ACR_WDL_HAMR { type = "trade_weapons"; buy[] ={9500,"Coins"}; sell[] ={4750,"Coins"}; };
class FHQ_ACR_WDL_HAMR_F { type = "trade_weapons"; buy[] ={9500,"Coins"}; sell[] ={4750,"Coins"}; };
class FHQ_ACR_WDL_HAMR_GL { type = "trade_weapons"; buy[] ={9800,"Coins"}; sell[] ={4900,"Coins"}; };
class FHQ_ACR_WDL_HAMR_GL_F { type = "trade_weapons"; buy[] ={9800,"Coins"}; sell[] ={4900,"Coins"}; };
class FHQ_ACR_BLK_IRN { type = "trade_weapons"; buy[] ={8000,"Coins"}; sell[] ={4000,"Coins"}; };
class FHQ_ACR_BLK_IRN_F { type = "trade_weapons"; buy[] ={8000,"Coins"}; sell[] ={4000,"Coins"}; };
class FHQ_ACR_BLK_IRN_GL { type = "trade_weapons"; buy[] ={8300,"Coins"}; sell[] ={4150,"Coins"}; };
class FHQ_ACR_BLK_IRN_GL_F { type = "trade_weapons"; buy[] ={8300,"Coins"}; sell[] ={4150,"Coins"}; };
class FHQ_ACR_BLK_CCO { type = "trade_weapons"; buy[] ={8500,"Coins"}; sell[] ={4250,"Coins"}; };
class FHQ_ACR_BLK_CCO_F { type = "trade_weapons"; buy[] ={8500,"Coins"}; sell[] ={4250,"Coins"}; };
class FHQ_ACR_BLK_CCO_GL { type = "trade_weapons"; buy[] ={8800,"Coins"}; sell[] ={4400,"Coins"}; };
class FHQ_ACR_BLK_CCO_GL_F { type = "trade_weapons"; buy[] ={8800,"Coins"}; sell[] ={4400,"Coins"}; };
class FHQ_ACR_BLK_RCO { type = "trade_weapons"; buy[] ={9500,"Coins"}; sell[] ={4750,"Coins"}; };
class FHQ_ACR_BLK_RCO_F { type = "trade_weapons"; buy[] ={9500,"Coins"}; sell[] ={4750,"Coins"}; };
class FHQ_ACR_BLK_RCO_GL { type = "trade_weapons"; buy[] ={9800,"Coins"}; sell[] ={4900,"Coins"}; };
class FHQ_ACR_BLK_RCO_GL_F { type = "trade_weapons"; buy[] ={9800,"Coins"}; sell[] ={4900,"Coins"}; };
class FHQ_ACR_BLK_HWS { type = "trade_weapons"; buy[] ={8500,"Coins"}; sell[] ={4250,"Coins"}; };
class FHQ_ACR_BLK_HWS_F { type = "trade_weapons"; buy[] ={8500,"Coins"}; sell[] ={4250,"Coins"}; };
class FHQ_ACR_BLK_HWS_GL { type = "trade_weapons"; buy[] ={8800,"Coins"}; sell[] ={4400,"Coins"}; };
class FHQ_ACR_BLK_HWS_GL_F { type = "trade_weapons"; buy[] ={8800,"Coins"}; sell[] ={4400,"Coins"}; };
class FHQ_ACR_BLK_G33 { type = "trade_weapons"; buy[] ={9500,"Coins"}; sell[] ={4750,"Coins"}; };
class FHQ_ACR_BLK_G33_F { type = "trade_weapons"; buy[] ={9500,"Coins"}; sell[] ={4750,"Coins"}; };
class FHQ_ACR_BLK_G33_GL { type = "trade_weapons"; buy[] ={9800,"Coins"}; sell[] ={4900,"Coins"}; };
class FHQ_ACR_BLK_G33_GL_F { type = "trade_weapons"; buy[] ={9800,"Coins"}; sell[] ={4900,"Coins"}; };
class FHQ_ACR_BLK_HAMR { type = "trade_weapons"; buy[] ={9500,"Coins"}; sell[] ={4750,"Coins"}; };
class FHQ_ACR_BLK_HAMR_F { type = "trade_weapons"; buy[] ={9500,"Coins"}; sell[] ={4750,"Coins"}; };
class FHQ_ACR_BLK_HAMR_GL { type = "trade_weapons"; buy[] ={9800,"Coins"}; sell[] ={4900,"Coins"}; };
class FHQ_ACR_BLK_HAMR_GL_F { type = "trade_weapons"; buy[] ={9800,"Coins"}; sell[] ={4900,"Coins"}; };
class FHQ_ACR_TAN_IRN { type = "trade_weapons"; buy[] ={8000,"Coins"}; sell[] ={4000,"Coins"}; };
class FHQ_ACR_TAN_IRN_F { type = "trade_weapons"; buy[] ={8000,"Coins"}; sell[] ={4000,"Coins"}; };
class FHQ_ACR_TAN_IRN_GL { type = "trade_weapons"; buy[] ={8300,"Coins"}; sell[] ={4150,"Coins"}; };
class FHQ_ACR_TAN_IRN_GL_F { type = "trade_weapons"; buy[] ={8300,"Coins"}; sell[] ={4150,"Coins"}; };
class FHQ_ACR_TAN_CCO { type = "trade_weapons"; buy[] ={8500,"Coins"}; sell[] ={4250,"Coins"}; };
class FHQ_ACR_TAN_CCO_F { type = "trade_weapons"; buy[] ={8500,"Coins"}; sell[] ={4250,"Coins"}; };
class FHQ_ACR_TAN_CCO_GL { type = "trade_weapons"; buy[] ={8800,"Coins"}; sell[] ={4400,"Coins"}; };
class FHQ_ACR_TAN_CCO_GL_F { type = "trade_weapons"; buy[] ={8800,"Coins"}; sell[] ={4400,"Coins"}; };
class FHQ_ACR_TAN_RCO { type = "trade_weapons"; buy[] ={9500,"Coins"}; sell[] ={4750,"Coins"}; };
class FHQ_ACR_TAN_RCO_F { type = "trade_weapons"; buy[] ={9500,"Coins"}; sell[] ={4750,"Coins"}; };
class FHQ_ACR_TAN_RCO_GL { type = "trade_weapons"; buy[] ={9800,"Coins"}; sell[] ={4900,"Coins"}; };
class FHQ_ACR_TAN_RCO_GL_F { type = "trade_weapons"; buy[] ={9800,"Coins"}; sell[] ={4900,"Coins"}; };
class FHQ_ACR_TAN_HWS { type = "trade_weapons"; buy[] ={8500,"Coins"}; sell[] ={4250,"Coins"}; };
class FHQ_ACR_TAN_HWS_F { type = "trade_weapons"; buy[] ={8500,"Coins"}; sell[] ={4250,"Coins"}; };
class FHQ_ACR_TAN_HWS_GL { type = "trade_weapons"; buy[] ={8800,"Coins"}; sell[] ={4400,"Coins"}; };
class FHQ_ACR_TAN_HWS_GL_F { type = "trade_weapons"; buy[] ={8800,"Coins"}; sell[] ={4400,"Coins"}; };
class FHQ_ACR_TAN_G33 { type = "trade_weapons"; buy[] ={9500,"Coins"}; sell[] ={4750,"Coins"}; };
class FHQ_ACR_TAN_G33_F { type = "trade_weapons"; buy[] ={9500,"Coins"}; sell[] ={4750,"Coins"}; };
class FHQ_ACR_TAN_G33_GL { type = "trade_weapons"; buy[] ={9800,"Coins"}; sell[] ={4900,"Coins"}; };
class FHQ_ACR_TAN_G33_GL_F { type = "trade_weapons"; buy[] ={9800,"Coins"}; sell[] ={4900,"Coins"}; };
class FHQ_ACR_TAN_HAMR { type = "trade_weapons"; buy[] ={9500,"Coins"}; sell[] ={4750,"Coins"}; };
class FHQ_ACR_TAN_HAMR_F { type = "trade_weapons"; buy[] ={9500,"Coins"}; sell[] ={4750,"Coins"}; };
class FHQ_ACR_TAN_HAMR_GL { type = "trade_weapons"; buy[] ={9800,"Coins"}; sell[] ={4900,"Coins"}; };
class FHQ_ACR_TAN_HAMR_GL_F { type = "trade_weapons"; buy[] ={9800,"Coins"}; sell[] ={4900,"Coins"}; };
class FHQ_ACR_SNW_IRN { type = "trade_weapons"; buy[] ={8000,"Coins"}; sell[] ={4000,"Coins"}; };
class FHQ_ACR_SNW_IRN_F { type = "trade_weapons"; buy[] ={8000,"Coins"}; sell[] ={4000,"Coins"}; };
class FHQ_ACR_SNW_IRN_GL { type = "trade_weapons"; buy[] ={8300,"Coins"}; sell[] ={4150,"Coins"}; };
class FHQ_ACR_SNW_IRN_GL_F { type = "trade_weapons"; buy[] ={8300,"Coins"}; sell[] ={4150,"Coins"}; };
class FHQ_ACR_SNW_CCO { type = "trade_weapons"; buy[] ={8500,"Coins"}; sell[] ={4250,"Coins"}; };
class FHQ_ACR_SNW_CCO_F { type = "trade_weapons"; buy[] ={8500,"Coins"}; sell[] ={4250,"Coins"}; };
class FHQ_ACR_SNW_CCO_GL { type = "trade_weapons"; buy[] ={8800,"Coins"}; sell[] ={4400,"Coins"}; };
class FHQ_ACR_SNW_CCO_GL_F { type = "trade_weapons"; buy[] ={8800,"Coins"}; sell[] ={4400,"Coins"}; };
class FHQ_ACR_SNW_RCO { type = "trade_weapons"; buy[] ={9500,"Coins"}; sell[] ={4750,"Coins"}; };
class FHQ_ACR_SNW_RCO_F { type = "trade_weapons"; buy[] ={9500,"Coins"}; sell[] ={4750,"Coins"}; };
class FHQ_ACR_SNW_RCO_GL { type = "trade_weapons"; buy[] ={9800,"Coins"}; sell[] ={4900,"Coins"}; };
class FHQ_ACR_SNW_RCO_GL_F { type = "trade_weapons"; buy[] ={9800,"Coins"}; sell[] ={4900,"Coins"}; };
class FHQ_ACR_SNW_HWS { type = "trade_weapons"; buy[] ={8500,"Coins"}; sell[] ={4250,"Coins"}; };
class FHQ_ACR_SNW_HWS_F { type = "trade_weapons"; buy[] ={8500,"Coins"}; sell[] ={4250,"Coins"}; };
class FHQ_ACR_SNW_HWS_GL { type = "trade_weapons"; buy[] ={8800,"Coins"}; sell[] ={4400,"Coins"}; };
class FHQ_ACR_SNW_HWS_GL_F { type = "trade_weapons"; buy[] ={8800,"Coins"}; sell[] ={4400,"Coins"}; };
class FHQ_ACR_SNW_G33 { type = "trade_weapons"; buy[] ={9500,"Coins"}; sell[] ={4750,"Coins"}; };
class FHQ_ACR_SNW_G33_F { type = "trade_weapons"; buy[] ={9500,"Coins"}; sell[] ={4750,"Coins"}; };
class FHQ_ACR_SNW_G33_GL { type = "trade_weapons"; buy[] ={9800,"Coins"}; sell[] ={4900,"Coins"}; };
class FHQ_ACR_SNW_G33_GL_F { type = "trade_weapons"; buy[] ={9800,"Coins"}; sell[] ={4900,"Coins"}; };
class FHQ_ACR_SNW_HAMR { type = "trade_weapons"; buy[] ={9500,"Coins"}; sell[] ={4750,"Coins"}; };
class FHQ_ACR_SNW_HAMR_F { type = "trade_weapons"; buy[] ={9500,"Coins"}; sell[] ={4750,"Coins"}; };
class FHQ_ACR_SNW_HAMR_GL { type = "trade_weapons"; buy[] ={9800,"Coins"}; sell[] ={4900,"Coins"}; };
class FHQ_ACR_SNW_HAMR_GL_F { type = "trade_weapons"; buy[] ={9800,"Coins"}; sell[] ={4900,"Coins"}; };
};
class Category_1490 {
class FHQ_ACR_WDL_IRN_SD { type = "trade_weapons"; buy[] ={10000,"Coins"}; sell[] ={5000,"Coins"}; };
class FHQ_ACR_WDL_IRN_SD_F { type = "trade_weapons"; buy[] ={10000,"Coins"}; sell[] ={5000,"Coins"}; };
class FHQ_ACR_WDL_IRN_GL_SD { type = "trade_weapons"; buy[] ={10300,"Coins"}; sell[] ={5150,"Coins"}; };
class FHQ_ACR_WDL_IRN_GL_SD_F { type = "trade_weapons"; buy[] ={10300,"Coins"}; sell[] ={5150,"Coins"}; };
class FHQ_ACR_WDL_CCO_SD { type = "trade_weapons"; buy[] ={10500,"Coins"}; sell[] ={5250,"Coins"}; };
class FHQ_ACR_WDL_CCO_SD_F { type = "trade_weapons"; buy[] ={10500,"Coins"}; sell[] ={5250,"Coins"}; };
class FHQ_ACR_WDL_CCO_GL_SD { type = "trade_weapons"; buy[] ={10800,"Coins"}; sell[] ={5400,"Coins"}; };
class FHQ_ACR_WDL_CCO_GL_SD_F { type = "trade_weapons"; buy[] ={10800,"Coins"}; sell[] ={5400,"Coins"}; };
class FHQ_ACR_WDL_RCO_SD { type = "trade_weapons"; buy[] ={11500,"Coins"}; sell[] ={5750,"Coins"}; };
class FHQ_ACR_WDL_RCO_SD_F { type = "trade_weapons"; buy[] ={11500,"Coins"}; sell[] ={5750,"Coins"}; };
class FHQ_ACR_WDL_RCO_GL_SD { type = "trade_weapons"; buy[] ={11800,"Coins"}; sell[] ={5900,"Coins"}; };
class FHQ_ACR_WDL_RCO_GL_SD_F { type = "trade_weapons"; buy[] ={11800,"Coins"}; sell[] ={5900,"Coins"}; };
class FHQ_ACR_WDL_HWS_SD { type = "trade_weapons"; buy[] ={10500,"Coins"}; sell[] ={5250,"Coins"}; };
class FHQ_ACR_WDL_HWS_SD_F { type = "trade_weapons"; buy[] ={10500,"Coins"}; sell[] ={5250,"Coins"}; };
class FHQ_ACR_WDL_HWS_GL_SD { type = "trade_weapons"; buy[] ={10800,"Coins"}; sell[] ={5400,"Coins"}; };
class FHQ_ACR_WDL_HWS_GL_SD_F { type = "trade_weapons"; buy[] ={10800,"Coins"}; sell[] ={5400,"Coins"}; };
class FHQ_ACR_WDL_G33_SD { type = "trade_weapons"; buy[] ={11500,"Coins"}; sell[] ={5750,"Coins"}; };
class FHQ_ACR_WDL_G33_SD_F { type = "trade_weapons"; buy[] ={11500,"Coins"}; sell[] ={5750,"Coins"}; };
class FHQ_ACR_WDL_G33_GL_SD { type = "trade_weapons"; buy[] ={11800,"Coins"}; sell[] ={5900,"Coins"}; };
class FHQ_ACR_WDL_G33_GL_SD_F { type = "trade_weapons"; buy[] ={11800,"Coins"}; sell[] ={5900,"Coins"}; };
class FHQ_ACR_WDL_HAMR_SD { type = "trade_weapons"; buy[] ={11500,"Coins"}; sell[] ={5750,"Coins"}; };
class FHQ_ACR_WDL_HAMR_SD_F { type = "trade_weapons"; buy[] ={11500,"Coins"}; sell[] ={5750,"Coins"}; };
class FHQ_ACR_WDL_HAMR_GL_SD { type = "trade_weapons"; buy[] ={11800,"Coins"}; sell[] ={5900,"Coins"}; };
class FHQ_ACR_WDL_HAMR_GL_SD_F { type = "trade_weapons"; buy[] ={11800,"Coins"}; sell[] ={5900,"Coins"}; };
class FHQ_ACR_BLK_IRN_SD { type = "trade_weapons"; buy[] ={10000,"Coins"}; sell[] ={5000,"Coins"}; };
class FHQ_ACR_BLK_IRN_SD_F { type = "trade_weapons"; buy[] ={10000,"Coins"}; sell[] ={5000,"Coins"}; };
class FHQ_ACR_BLK_IRN_GL_SD { type = "trade_weapons"; buy[] ={10300,"Coins"}; sell[] ={5150,"Coins"}; };
class FHQ_ACR_BLK_IRN_GL_SD_F { type = "trade_weapons"; buy[] ={10300,"Coins"}; sell[] ={5150,"Coins"}; };
class FHQ_ACR_BLK_CCO_SD { type = "trade_weapons"; buy[] ={10500,"Coins"}; sell[] ={5250,"Coins"}; };
class FHQ_ACR_BLK_CCO_SD_F { type = "trade_weapons"; buy[] ={10500,"Coins"}; sell[] ={5250,"Coins"}; };
class FHQ_ACR_BLK_CCO_GL_SD { type = "trade_weapons"; buy[] ={10800,"Coins"}; sell[] ={5400,"Coins"}; };
class FHQ_ACR_BLK_CCO_GL_SD_F { type = "trade_weapons"; buy[] ={10800,"Coins"}; sell[] ={5400,"Coins"}; };
class FHQ_ACR_BLK_RCO_SD { type = "trade_weapons"; buy[] ={11500,"Coins"}; sell[] ={5750,"Coins"}; };
class FHQ_ACR_BLK_RCO_SD_F { type = "trade_weapons"; buy[] ={11500,"Coins"}; sell[] ={5750,"Coins"}; };
class FHQ_ACR_BLK_RCO_GL_SD { type = "trade_weapons"; buy[] ={11800,"Coins"}; sell[] ={5900,"Coins"}; };
class FHQ_ACR_BLK_RCO_GL_SD_F { type = "trade_weapons"; buy[] ={11800,"Coins"}; sell[] ={5900,"Coins"}; };
class FHQ_ACR_BLK_HWS_SD { type = "trade_weapons"; buy[] ={10500,"Coins"}; sell[] ={5250,"Coins"}; };
class FHQ_ACR_BLK_HWS_SD_F { type = "trade_weapons"; buy[] ={10500,"Coins"}; sell[] ={5250,"Coins"}; };
class FHQ_ACR_BLK_HWS_GL_SD { type = "trade_weapons"; buy[] ={10800,"Coins"}; sell[] ={5400,"Coins"}; };
class FHQ_ACR_BLK_HWS_GL_SD_F { type = "trade_weapons"; buy[] ={10800,"Coins"}; sell[] ={5400,"Coins"}; };
class FHQ_ACR_BLK_G33_SD { type = "trade_weapons"; buy[] ={11500,"Coins"}; sell[] ={5750,"Coins"}; };
class FHQ_ACR_BLK_G33_SD_F { type = "trade_weapons"; buy[] ={11500,"Coins"}; sell[] ={5750,"Coins"}; };
class FHQ_ACR_BLK_G33_GL_SD { type = "trade_weapons"; buy[] ={11800,"Coins"}; sell[] ={5900,"Coins"}; };
class FHQ_ACR_BLK_G33_GL_SD_F { type = "trade_weapons"; buy[] ={11800,"Coins"}; sell[] ={5900,"Coins"}; };
class FHQ_ACR_BLK_HAMR_SD { type = "trade_weapons"; buy[] ={11500,"Coins"}; sell[] ={5750,"Coins"}; };
class FHQ_ACR_BLK_HAMR_SD_F { type = "trade_weapons"; buy[] ={11500,"Coins"}; sell[] ={5750,"Coins"}; };
class FHQ_ACR_BLK_HAMR_GL_SD { type = "trade_weapons"; buy[] ={11800,"Coins"}; sell[] ={5900,"Coins"}; };
class FHQ_ACR_BLK_HAMR_GL_SD_F { type = "trade_weapons"; buy[] ={11800,"Coins"}; sell[] ={5900,"Coins"}; };
class FHQ_ACR_TAN_IRN_SD { type = "trade_weapons"; buy[] ={10000,"Coins"}; sell[] ={5000,"Coins"}; };
class FHQ_ACR_TAN_IRN_SD_F { type = "trade_weapons"; buy[] ={10000,"Coins"}; sell[] ={5000,"Coins"}; };
class FHQ_ACR_TAN_IRN_GL_SD { type = "trade_weapons"; buy[] ={10300,"Coins"}; sell[] ={5150,"Coins"}; };
class FHQ_ACR_TAN_IRN_GL_SD_F { type = "trade_weapons"; buy[] ={10300,"Coins"}; sell[] ={5150,"Coins"}; };
class FHQ_ACR_TAN_CCO_SD { type = "trade_weapons"; buy[] ={10500,"Coins"}; sell[] ={5250,"Coins"}; };
class FHQ_ACR_TAN_CCO_SD_F { type = "trade_weapons"; buy[] ={10500,"Coins"}; sell[] ={5250,"Coins"}; };
class FHQ_ACR_TAN_CCO_GL_SD { type = "trade_weapons"; buy[] ={10800,"Coins"}; sell[] ={5400,"Coins"}; };
class FHQ_ACR_TAN_CCO_GL_SD_F { type = "trade_weapons"; buy[] ={10800,"Coins"}; sell[] ={5400,"Coins"}; };
class FHQ_ACR_TAN_RCO_SD { type = "trade_weapons"; buy[] ={11500,"Coins"}; sell[] ={5750,"Coins"}; };
class FHQ_ACR_TAN_RCO_SD_F { type = "trade_weapons"; buy[] ={11500,"Coins"}; sell[] ={5750,"Coins"}; };
class FHQ_ACR_TAN_RCO_GL_SD { type = "trade_weapons"; buy[] ={11800,"Coins"}; sell[] ={5900,"Coins"}; };
class FHQ_ACR_TAN_RCO_GL_SD_F { type = "trade_weapons"; buy[] ={11800,"Coins"}; sell[] ={5900,"Coins"}; };
class FHQ_ACR_TAN_HWS_SD { type = "trade_weapons"; buy[] ={10500,"Coins"}; sell[] ={5250,"Coins"}; };
class FHQ_ACR_TAN_HWS_SD_F { type = "trade_weapons"; buy[] ={10500,"Coins"}; sell[] ={5250,"Coins"}; };
class FHQ_ACR_TAN_HWS_GL_SD { type = "trade_weapons"; buy[] ={10800,"Coins"}; sell[] ={5400,"Coins"}; };
class FHQ_ACR_TAN_HWS_GL_SD_F { type = "trade_weapons"; buy[] ={10800,"Coins"}; sell[] ={5400,"Coins"}; };
class FHQ_ACR_TAN_G33_SD { type = "trade_weapons"; buy[] ={11500,"Coins"}; sell[] ={5750,"Coins"}; };
class FHQ_ACR_TAN_G33_SD_F { type = "trade_weapons"; buy[] ={11500,"Coins"}; sell[] ={5750,"Coins"}; };
class FHQ_ACR_TAN_G33_GL_SD { type = "trade_weapons"; buy[] ={11800,"Coins"}; sell[] ={5900,"Coins"}; };
class FHQ_ACR_TAN_G33_GL_SD_F { type = "trade_weapons"; buy[] ={11800,"Coins"}; sell[] ={5900,"Coins"}; };
class FHQ_ACR_TAN_HAMR_SD { type = "trade_weapons"; buy[] ={11500,"Coins"}; sell[] ={5750,"Coins"}; };
class FHQ_ACR_TAN_HAMR_SD_F { type = "trade_weapons"; buy[] ={11500,"Coins"}; sell[] ={5750,"Coins"}; };
class FHQ_ACR_TAN_HAMR_GL_SD { type = "trade_weapons"; buy[] ={11800,"Coins"}; sell[] ={5900,"Coins"}; };
class FHQ_ACR_TAN_HAMR_GL_SD_F { type = "trade_weapons"; buy[] ={11800,"Coins"}; sell[] ={5900,"Coins"}; };
class FHQ_ACR_SNW_IRN_SD { type = "trade_weapons"; buy[] ={10000,"Coins"}; sell[] ={5000,"Coins"}; };
class FHQ_ACR_SNW_IRN_SD_F { type = "trade_weapons"; buy[] ={10000,"Coins"}; sell[] ={5000,"Coins"}; };
class FHQ_ACR_SNW_IRN_GL_SD { type = "trade_weapons"; buy[] ={10300,"Coins"}; sell[] ={5150,"Coins"}; };
class FHQ_ACR_SNW_IRN_GL_SD_F { type = "trade_weapons"; buy[] ={10300,"Coins"}; sell[] ={5150,"Coins"}; };
class FHQ_ACR_SNW_CCO_SD { type = "trade_weapons"; buy[] ={10500,"Coins"}; sell[] ={5250,"Coins"}; };
class FHQ_ACR_SNW_CCO_SD_F { type = "trade_weapons"; buy[] ={10500,"Coins"}; sell[] ={5250,"Coins"}; };
class FHQ_ACR_SNW_CCO_GL_SD { type = "trade_weapons"; buy[] ={10800,"Coins"}; sell[] ={5400,"Coins"}; };
class FHQ_ACR_SNW_CCO_GL_SD_F { type = "trade_weapons"; buy[] ={10800,"Coins"}; sell[] ={5400,"Coins"}; };
class FHQ_ACR_SNW_RCO_SD { type = "trade_weapons"; buy[] ={11500,"Coins"}; sell[] ={5750,"Coins"}; };
class FHQ_ACR_SNW_RCO_SD_F { type = "trade_weapons"; buy[] ={11500,"Coins"}; sell[] ={5750,"Coins"}; };
class FHQ_ACR_SNW_RCO_GL_SD { type = "trade_weapons"; buy[] ={11800,"Coins"}; sell[] ={5900,"Coins"}; };
class FHQ_ACR_SNW_RCO_GL_SD_F { type = "trade_weapons"; buy[] ={11800,"Coins"}; sell[] ={5900,"Coins"}; };
class FHQ_ACR_SNW_HWS_SD { type = "trade_weapons"; buy[] ={10500,"Coins"}; sell[] ={5250,"Coins"}; };
class FHQ_ACR_SNW_HWS_SD_F { type = "trade_weapons"; buy[] ={10500,"Coins"}; sell[] ={5250,"Coins"}; };
class FHQ_ACR_SNW_HWS_GL_SD { type = "trade_weapons"; buy[] ={10800,"Coins"}; sell[] ={5400,"Coins"}; };
class FHQ_ACR_SNW_HWS_GL_SD_F { type = "trade_weapons"; buy[] ={10800,"Coins"}; sell[] ={5400,"Coins"}; };
class FHQ_ACR_SNW_G33_SD { type = "trade_weapons"; buy[] ={11500,"Coins"}; sell[] ={5750,"Coins"}; };
class FHQ_ACR_SNW_G33_SD_F { type = "trade_weapons"; buy[] ={11500,"Coins"}; sell[] ={5750,"Coins"}; };
class FHQ_ACR_SNW_G33_GL_SD { type = "trade_weapons"; buy[] ={11800,"Coins"}; sell[] ={5900,"Coins"}; };
class FHQ_ACR_SNW_G33_GL_SD_F { type = "trade_weapons"; buy[] ={11800,"Coins"}; sell[] ={5900,"Coins"}; };
class FHQ_ACR_SNW_HAMR_SD { type = "trade_weapons"; buy[] ={11500,"Coins"}; sell[] ={5750,"Coins"}; };
class FHQ_ACR_SNW_HAMR_SD_F { type = "trade_weapons"; buy[] ={11500,"Coins"}; sell[] ={5750,"Coins"}; };
class FHQ_ACR_SNW_HAMR_GL_SD { type = "trade_weapons"; buy[] ={11800,"Coins"}; sell[] ={5900,"Coins"}; };
class FHQ_ACR_SNW_HAMR_GL_SD_F { type = "trade_weapons"; buy[] ={11800,"Coins"}; sell[] ={5900,"Coins"}; };
};
class Category_1415 {
class FHQ_MSR_DESERT { type = "trade_weapons"; buy[] ={30000,"Coins"}; sell[] ={15000,"Coins"}; };
class FHQ_MSR_SD_DESERT { type = "trade_weapons"; buy[] ={35000,"Coins"}; sell[] ={17500,"Coins"}; };
class FHQ_MSR_NV_DESERT { type = "trade_weapons"; buy[] ={30000,"Coins"}; sell[] ={15000,"Coins"}; };
class FHQ_MSR_NV_SD_DESERT { type = "trade_weapons"; buy[] ={35000,"Coins"}; sell[] ={17500,"Coins"}; };
class FHQ_RSASS_TAN { type = "trade_weapons"; buy[] ={24000,"Coins"}; sell[] ={12000,"Coins"}; };
class FHQ_RSASS_SD_TAN { type = "trade_weapons"; buy[] ={30000,"Coins"}; sell[] ={15000,"Coins"}; };
class FHQ_XM2010_DESERT { type = "trade_weapons"; buy[] ={28000,"Coins"}; sell[] ={14000,"Coins"}; };
class FHQ_XM2010_SD_DESERT { type = "trade_weapons"; buy[] ={35000,"Coins"}; sell[] ={17500,"Coins"}; };
class FHQ_XM2010_NV_DESERT { type = "trade_weapons"; buy[] ={28000,"Coins"}; sell[] ={14000,"Coins"}; };
class FHQ_XM2010_NV_SD_DESERT { type = "trade_weapons"; buy[] ={35000,"Coins"}; sell[] ={17500,"Coins"}; };
class vil_SVD_63 { type = "trade_weapons"; buy[] ={16000,"Coins"}; sell[] ={8000,"Coins"}; };
class vil_SVD_N { type = "trade_weapons"; buy[] ={16000,"Coins"}; sell[] ={8000,"Coins"}; };
class vil_SVD_S { type = "trade_weapons"; buy[] ={16000,"Coins"}; sell[] ={8000,"Coins"}; };
class vil_SVD_M { type = "trade_weapons"; buy[] ={16000,"Coins"}; sell[] ={8000,"Coins"}; };
class vil_SVD_P21 { type = "trade_weapons"; buy[] ={16000,"Coins"}; sell[] ={8000,"Coins"}; };
class vil_SVDK { type = "trade_weapons"; buy[] ={20000,"Coins"}; sell[] ={10000,"Coins"}; };
class vil_SV_98 { type = "trade_weapons"; buy[] ={20000,"Coins"}; sell[] ={10000,"Coins"}; };
class vil_SV_98_69 { type = "trade_weapons"; buy[] ={20000,"Coins"}; sell[] ={10000,"Coins"}; };
class vil_SV_98_SD { type = "trade_weapons"; buy[] ={20000,"Coins"}; sell[] ={10000,"Coins"}; };
class gms_k98 { type = "trade_weapons"; buy[] ={1200,"Coins"}; sell[] ={600,"Coins"}; };
class gms_k98_rg { type = "trade_weapons"; buy[] ={1200,"Coins"}; sell[] ={600,"Coins"}; };
class gms_k98_knife { type = "trade_weapons"; buy[] ={1200,"Coins"}; sell[] ={600,"Coins"}; };
class gms_k98zf39 { type = "trade_weapons"; buy[] ={1200,"Coins"}; sell[] ={600,"Coins"}; };
};
class Category_3400{
class 30Rnd_556x45_Stanag { type = "trade_items"; buy[] ={120,"Coins"}; sell[] ={60,"Coins"}; };
class 30Rnd_556x45_StanagSD { type = "trade_items"; buy[] ={600,"Coins"}; sell[] ={150,"Coins"}; };
class RH_20Rnd_762x51_SD_hk417 { type = "trade_items"; buy[] ={240,"Coins"}; sell[] ={120,"Coins"}; };
class RH_20Rnd_762x51_hk417 { type = "trade_items"; buy[] ={180,"Coins"}; sell[] ={90,"Coins"}; };
class 20Rnd_762x51_DMR { type = "trade_items"; buy[] ={600,"Coins"}; sell[] ={300,"Coins"}; };
class 20rnd_762x51_B_SCAR { type = "trade_items"; buy[] ={900,"Coins"}; sell[] ={300,"Coins"}; };
class 20rnd_762x51_SB_SCAR { type = "trade_items"; buy[] ={1800,"Coins"}; sell[] ={600,"Coins"}; };
class FHQ_rem_30Rnd_680x43_ACR { type = "trade_items"; buy[] ={240,"Coins"}; sell[] ={120,"Coins"}; };
class FHQ_rem_30Rnd_680x43_ACR_SD { type = "trade_items"; buy[] ={900,"Coins"}; sell[] ={300,"Coins"}; };
class USSR_5Rnd_408 { type = "trade_items"; buy[] ={5000,"Coins"}; sell[] ={2500,"Coins"}; };
class FHQ_rem_7Rnd_338Lapua_MSR_NT { type = "trade_items"; buy[] ={1200,"Coins"}; sell[] ={400,"Coins"}; };
class FHQ_rem_7Rnd_338Lapua_MSR_NT_SD { type = "trade_items"; buy[] ={1800,"Coins"}; sell[] ={600,"Coins"}; };
class FHQ_rem_20Rnd_762x51_PMAG_NT { type = "trade_items"; buy[] ={1200,"Coins"}; sell[] ={400,"Coins"}; };
class FHQ_rem_20Rnd_762x51_PMAG_NT_SD { type = "trade_items"; buy[] ={1800,"Coins"}; sell[] ={600,"Coins"}; };
class FHQ_rem_5Rnd_300Win_XM2010_NT_SD { type = "trade_items"; buy[] ={1800,"Coins"}; sell[] ={600,"Coins"}; };
class FHQ_rem_5Rnd_300Win_XM2010_NT { type = "trade_items"; buy[] ={1200,"Coins"}; sell[] ={400,"Coins"}; };
class 10Rnd_762x54_SVD { type = "trade_items"; buy[] ={600,"Coins"}; sell[] ={30,"Coins"}; };
class vil_10Rnd_SVDK { type = "trade_items"; buy[] ={1200,"Coins"}; sell[] ={400,"Coins"}; };
class vil_10Rnd_762x54_SV { type = "trade_items"; buy[] ={1200,"Coins"}; sell[] ={400,"Coins"}; };
class gms_k98_mag { type = "trade_items"; buy[] ={600,"Coins"}; sell[] ={200,"Coins"}; };
};

